### PR TITLE
implement eeprom driver and rgb matrix

### PR DESCRIPTION
**Pull request by zhaqian12**
add the support of eeprom driver to write stably
1.eeprom custom
2.eeprom wear leveing from qmk develop
3.add the support of ws2812 pwm dma driver
4.add the support of qmk rgb matrix
5.add common_features.cmake and rules.cmake to conditional compile

### CODE REVIEW

**Comment by Huckies** [comment]
Hi zhaqian,

Thank you for the PR, while some polish is needed I'm afraid.

The macro ``QMK_EEPROM_START_POSITION`` in ``eeprom.h``--which I believe you removed it is used to set the offset of QMK firmware in DataFlash. Since there is a plan to add Bluetooth LE support it's necessary to preserve the first few bytes for the stack. It seems to slipping out of my mind when implementing the eeprom driver, would you please make it up?

**Comment by zhaqian12** [comment]
Okay, I've fixed it.

**Comment by OctopusZ** [comment]
Hi zhaqian
谢谢你对仓库的关注和贡献。
但是2812的PWM驱动方面还有一些问题。
无论是RGB_MATRIX或者RGBLIGHT，都无法正常点亮2812。
可能定时器的分频参数存在问题。
在实际测试中，（RGB_MATRIX_ENABLE = NO；RGBLIGHT_ENABLE = YES；WS2812_DRIVER = pwm） 
IO A10的波形如下，无法驱动ws2812.
微信图片_20220815195328

**Comment by Huckies** [comment]
@zhaqian12 

Hi zhaqian,

Just to let you know, I've checked the eeprom part so your PR should be merged right after the pwm driver is verified by @OctopusZ as I don't have an adequate dk.

**Comment by zhaqian12** [comment]
Okay,thanks for your reply.

**Review by Huckies — APPROVED** [review]

**Pull request merged**
